name: Check

on:
  push:
    branches:
      - main
    paths:
      - crosshair/**
      - setup.py
      - .pre-commit-config.yaml

  pull_request:
    paths:
      - crosshair/**
      - setup.py
      - .pre-commit-config.yaml

jobs:
  Execute:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [
          # There were breaking changes in 3.7.0 and we should test for it.
          # Unfortunately, GitHub does not support Python 3.7.0.
          "3.7.1",
          "3.8",
          "3.9",
          "3.10",
        ]
        # Tests only pass for certain python versions, and seems to hang when
        # tun in CI right now :(
        # include:
        #   - os: windows-2016
        #     python_version: "3.8.9"

    steps:
      - uses: actions/checkout@main

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          # Vanilla install and smoke test, just to make sure we do
          # not accidentally add an import for a [dev] dependency:
          pip3 install -e .
          crosshair -h
          # Now add the dev dependencies, so we can use them for testing.
          pip3 install -e .[dev]

      - name: Run checks
        run: |
          pre-commit run --all-files --hook-stage manual
